security:
  oauth2:
    client:
      client-id: client_id
      client_secret: secret
      access-token-validity-seconds: 3600
      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
      scope: READ,WRITE